# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 4, 20, 27, 52, 167187, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
